apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Daemon       off
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/*fluent-bit*.log, /var/log/containers/*coredns*.log, /var/log/containers/*kube-controller-manager*.log, /var/log/containers/*storage-provisioner*.log, /var/log/containers/*kube-scheduler*.log, /var/log/containers/*kube-proxy*.log, /var/log/containers/*kube-apiserver*.log, /var/log/containers/*etcd*.log  
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        DB                /var/log/flb_kube.db

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name          loki
        Match         *
        Host          127.0.0.1
        Uri           /loki/api/v1/push
        labels        job=fluent_bit
        Port          3100
        # tls           On
        # tls.verify    Off
        remove_keys   stream
  parsers.conf: |
    [PARSER]
        Name              docker
        Format            json
        Time_Key          time
        Time_Format       %Y-%m-%dT%H:%M:%S.%L
        Time_Keep         On