apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring  # Use this if you created a namespace; otherwise, remove this line
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:2
        ports:
        - containerPort: 8086
        env:
          - name: INFLUXDB_DB
            value: "influxdb"
          - name: INFLUXDB_USER
            value: "arin"     
          - name: INFLUXDB_PASSWORD
            value: "12345678" 
        volumeMounts:
          - name: influxdb-storage
            mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-storage
          emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring  
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30086 
  selector:
    app: influxdb
