apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000  # NodePort range is typically 30000-32767
